Repository jincde/before-trip, pull requests merged in 2022-12, with the labels that each got.

#40 Fix: 로그인하면 회원가입 안되게하는 기능추가
  accounts/templates/accounts/signup.html
  accounts/views.py
Labels: chore, fix, test

#41 Fix: 회원가입시 프로필 이미지 안들어가는거 자스로 해결 완료
  accounts/templates/accounts/signup.html
Labels: FE, help

#44 Feat: 나라별 뉴스 파싱한거 추가 완료
  countries/models.py
  countries/templates/countries/detail.html
  countries/views.py
  news.py
  news2.json
Labels: BE, feature

#45 Feat: 실시간 날씨 기능 완료
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, feature

#46 Feat: 파파고 번역 기능
  communities/templates/communities/test.html
  country.py
Labels: feature

#49 Fix : merge 후 div 수정
  communities/templates/communities/index.html
Labels: fix

#50 Style: 리뷰 디테일 스타일 추가
  PJT/settings.py
  communities/admin.py
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
  communities/views.py
Labels: FE, style, fix

#51 Fix : 회원가입 시 유효성 피드백 제공 기능
  accounts/templates/accounts/signup.html
  static/css/accounts.css
Labels: FE, style

#55 Fix: 번역 기능 최적화
  country.py
Labels: fix

#56 Style: 작성된 댓글이 없습니다 추가
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
Labels: style

#58 Style : 회원 디테일 페이지 초안
  accounts/templates/accounts/detail.html
Labels: FE, style

#59 Feat: 날짜별로 날씨예보 기능 추가
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, feature

#63 Test: 댓글 비동기, Style: 썸머노트 버튼 수정
  PJT/settings.py
  communities/templates/communities/detail.html
  communities/templates/communities/test.html
  communities/urls.py
  communities/views.py
Labels: style, test

#65 Feat: 댓글 비동기 Create 완성
  communities/templates/communities/detail.html
  communities/templates/communities/test.html
  communities/urls.py
  communities/views.py
Labels: feature

#66 Feat: 날씨 예보 날짜 수정하고 환율 업데이트 기능 추가
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, feature, fix

#69 Style : 커뮤니티 작성 폼 디자인
  communities/templates/communities/form.html
Labels: FE, style

#70 Feat: 실시간 현지 시간 기능 추가
  PJT/settings.py
  countries/templates/countries/detail.html
  countries/views.py
  requirements.txt
Labels: FE, feature

#71 Feat: 대댓글 비동기 생성
  communities/templates/communities/detail.html
  communities/urls.py
  communities/views.py
Labels: BE, feature

#72 Feat: 나라별 환율 기능 완료
  countries/templates/countries/detail.html
  countries/views.py
Labels: BE, feature, done

#73 Refactor: country-detail 관련한 코드 정리
  countries/templates/countries/detail.html
  countries/views.py
Labels: refactor

#76 Feat: 나라별 현지시간 추가 완료
  countries/templates/countries/detail.html
  countries/views.py
Labels: BE, feature

#78 Style : 커뮤니티 인덱스 베스트 리뷰 스타일 변경
  communities/templates/communities/form.html
  communities/templates/communities/index.html
  static/css/main.css
Labels: FE, style

#79 Feat : 공지사항(Notice) 모델 추가
  communities/admin.py
  communities/models.py
Labels: chore, feature

#80 Fix : 투명 내브바 오류 수정
  communities/templates/communities/index.html
Labels: fix

#81 Fix: 부트스트랩 로그인폼 주석처리
  accounts/templates/accounts/login.html
Labels: FE, fix

#82 Fix : 프로필 사진 입력 input 숨기기
  accounts/templates/accounts/signup.html
  countries/templates/countries/detail.html
Labels: style, fix

#85 Feat:accounts app의 detail 분기처리
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/index.html
  accounts/templates/accounts/list.html
  accounts/views.py
Labels: FE, BE, feature

#88 Fix: FE 제대로 안나온거 수정 완료
  accounts/templates/accounts/detail.html
  accounts/views.py
Labels: FE, fix

#89 Fix : 모바일 검색 기능 개선
  communities/templates/communities/search.html
  static/css/trans_navbar.css
  static/img/menu.svg
  templates/white.html
Labels: style, fix

#90 Feat: 자스로 현지시계 구현
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, feature

#91 Style: 댓글 생성, 대댓글 생성 비동기 화면 구현
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
  communities/views.py
Labels: FE, style

#92 Fix: 자스 if문을 통해 나라별페이지별로 추가 완료
  countries/templates/countries/detail.html
  static/css/trans_navbar.css
Labels: FE, fix

#94 Fix: 날씨 불필요한 글씨 지우고 필요없는 코드 지우기 완료
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, chore, fix

#95 Style : 국가, 축제 카드 디자인
  countries/admin.py
  countries/models.py
  countries/templates/countries/detail.html
  countries/templates/countries/index.html
  countries/views.py
  static/css/main.css
  static/css/trans_navbar.css
  static/img/ico_now_moving.gif
  templates/base.html
  templates/map.html
  templates/white.html
Labels: FE, style

#96 Fix: 검색 안되는거 고치고 나라코드 안보이게 하는거 완료
  communities/templates/communities/search.html
  countries/templates/countries/detail.html
Labels: FE, BE, fix

#97 Chore: 비동기 답글 화면 구현
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
  communities/views.py
Labels: FE, style, chore

#99 Style: 비동기 대댓글 화면 구현
  .vscode/settings.json
  communities/templates/communities/detail.html
  communities/urls.py
  communities/views.py
Labels: FE, style

#100 Feat: 네브바 페이지 연결 완료
  templates/trans_navbar.html
  templates/white.html
Labels: FE, BE, feature

#101 Fix: 네브바 스크롤할때 글씨 바뀌는거 고치기 완료
  static/css/trans_navbar.css
  templates/trans_navbar.html
Labels: FE, style, fix

#102 Feat: 네브바에 로그인 로그아웃 프로필 띄우기 완료
  accounts/templates/accounts/index.html
  accounts/views.py
  templates/trans_navbar.html
  templates/white.html
Labels: FE, BE, feature

#103 Fix: 네브바 프로필 이미지 없을때 이미지 띄우는 고치기 완료
  templates/trans_navbar.html
  templates/white.html
Labels: FE, fix

#105 Style : 날씨 카드 도시별로 나누기
  countries/templates/countries/detail.html
  static/css/trans_navbar.css
  templates/white.html
Labels: FE, style

#106 Style: 나라별 커뮤니티 인덱스 페이지 스타일 추가
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
  communities/templates/communities/index.html
  communities/views.py
  static/images/미국국기.png
  static/images/미국사진1.jpg
  static/images/스페인국기.png
  static/images/스페인사진.jpg
  static/images/영국 사진 3.jpg
  static/images/영국국기.png
  static/images/일본국기.png
  static/images/일본사진1.jpg
  static/images/호주-australia-시드니-2.jpg
  static/images/호주국기.png
Labels: FE, style

#107 Style : 회원 디테일 디자인, 국가 디테일 디자인
  accounts/templates/accounts/detail.html
  countries/templates/countries/detail.html
  static/css/trans_navbar.css
  static/img/desktop.png
  static/img/note.png
  static/img/speech.png
Labels: FE, style

#109 Feat : 커뮤니티 인덱스 페이지 생성
  communities/templates/communities/main.html
  communities/templates/communities/search.html
  communities/urls.py
  communities/views.py
  templates/trans_navbar.html
Labels: feature

#110 Feat: 게시글 좋아요 기능 구현
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
  communities/urls.py
  communities/views.py
Labels: style, done

#111 Feat : 국가 디테일 페이지, 중요 정보 안내
  accounts/templates/accounts/detail.html
  countries/models.py
  countries/templates/countries/detail.html
Labels: FE

#112 Feat: 도시 날씨 하나 추가
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, feature

#113 Style : 날씨 카드 디자인
  countries/models.py
  countries/templates/countries/detail.html
Labels: FE, style

#114 Fix:날씨 시간 장소에 맞춰서 바꾸기 완료
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, fix

#115 Style: 회원 디테일 페이지 작성 댓글, 작성 게시물, 좋아요한 글 스타일 추가
  accounts/templates/accounts/detail.html
  accounts/views.py
  communities/static/communities/css/style.css
  templates/trans_navbar.html
Labels: FE, style

#116 Feat: 좋아요 게시글 기능 추가 및 불필요한 부분 고치기 완료
  accounts/templates/accounts/detail.html
  accounts/views.py
Labels: FE, BE, feature

#117 Feat : 커뮤니티 인덱스 carousel 추가
  accounts/templates/accounts/detail.html
  communities/templates/communities/index.html
  countries/templates/countries/detail.html
  templates/trans_navbar.html
  templates/white.html
Labels: FE, feature

#118 Feat : 프로필 편집, 로그아웃 연결
  accounts/templates/accounts/detail.html
  communities/static/communities/css/style.css
  communities/templates/communities/index.html
  countries/templates/countries/detail.html
Labels: FE

#119 Chore : 국가 인덱스 페이지 더미카드 삭제
  countries/templates/countries/index.html
Labels: chore

#121 Feat : 뉴스 데이터 추가
  countries/admin.py
  countries/models.py
  countries/templates/countries/detail.html
  countries/templates/countries/index.html
  static/css/main.css
Labels: FE

#123 Fix: 환율 원하는 값으로 불러오기 성공
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, fix

#125 Fix: accounts detail 오류 고치고 스타일 고쳤습니다.
  accounts/templates/accounts/detail.html
  accounts/views.py
Labels: FE, BE, fix

#126 Fix: 본인일때와 타인일때 필요한버튼 수정하기
  accounts/templates/accounts/detail.html
Labels: FE, BE, fix

#127 Fix: 메인 국가화면에 국가코드 지우기 완료
  countries/templates/countries/index.html
Labels: fix

#128 Style: 리뷰 디테일 모바일 환경 수정 삭제 추가
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
Labels: style

#129 Feat : 검색기능 완료
  communities/templates/communities/search.html
Labels: done

#130 Feat: 피드 기능 모두 구현 완료
  communities/forms.py
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
  communities/templates/communities/feed_index.html
  communities/templates/communities/feed_index_un.html
  communities/urls.py
  communities/views.py
Labels: FE, BE, feature

#131 Fix : 대체 사진 수정, 내브바 글씨 색상 변경
  communities/templates/communities/search.html
  countries/templates/countries/detail.html
  templates/trans_navbar.html
Labels: fix

#132 Fix : 작성 폼 grade, 대표사진
  communities/templates/communities/form.html
Labels: fix

#134 Feat:Communities Review Video 태그 삽입
  communities/static/communities/css/style.css
  communities/templates/communities/index.html
Labels: feature

#136 Chore: 업데이트폼에서 기존 날짜 기억하도록 수정
  communities/templates/communities/detail.html
  communities/templates/communities/form.html
  communities/views.py
Labels: FE, chore

#137 Chore: 디테일 날짜 수정
  communities/templates/communities/detail copy.html
  communities/templates/communities/detail.html
Labels: FE, chore

#139 Feat : 축제 나라별 가져오기
  countries/views.py
Labels: feature

#141 Fix: 업데이트 폼 수정
  communities/static/communities/css/style.css
  communities/templates/communities/form.html
  communities/templates/communities/index.html
Labels: FE, style

#142 Fix:Loading 수정
  countries/templates/countries/index.html
  templates/base.html
Labels: fix

#144 Style: 리뷰 수정 폼 이미지 출력 수정
  communities/static/communities/css/style.css
  communities/templates/communities/form.html
  communities/templates/communities/index.html
Labels: FE, chore

#145 Style: 리모컨바 댓글 수 비동기 반영
  communities/templates/communities/detail.html
Labels: FE, style

#146 Feat : 커뮤니티 인덱스 꿀팁, 피드 추가
  communities/templates/communities/main.html
Labels: feature

#147 Feat: 네브바에 커뮤니티 분기
  static/css/trans_navbar.css
  templates/base.html
  templates/trans_navbar.html
  templates/white.html
Labels: FE, feature

#148 Fix:구글 로고 안오는거 수정
  accounts/templates/accounts/login.html
  static/img/google-logo.jpg
Labels: FE, fix

#150 Fix: 햄버거 네브바에서 아코디언 출력
  templates/trans_navbar.html
  templates/white.html
Labels: chore

#152 Hg 09
  communities/templates/communities/detail.html
  communities/templates/communities/feed_index.html
  templates/white.html
Labels: fix

#154 Fix:어카운트 사진 안들어가는 문제 해결
  templates/white.html
Labels: FE, fix

#155 Fix: 환율 주석처리 해제
  countries/templates/countries/detail.html
  countries/views.py
Labels: FE, BE, fix

#156 Chore: 리뷰 디테일 자잘한 오류 수정
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
Labels: FE, chore

#157 Fix : 검색 이미지 사이즈 오류 해결
  communities/templates/communities/search.html
Labels: fix

#158 Chore : 메인 페이지 영문명 추가
  countries/templates/countries/index.html
Labels: chore

#159 Chore : 커뮤니티 인덱스 영문명 추가
  communities/templates/communities/main.html
Labels: chore

#160 Chore: 정리
  communities/admin.py
  communities/templates/communities/advice_form.html
  communities/templates/communities/detail.html
  communities/templates/communities/feed_index.html
  communities/templates/communities/form.html
  communities/templates/communities/index.html
  communities/templates/communities/main.html
  countries/templates/countries/index.html
  templates/not_nav_base.html
  templates/trans_navbar.html
  templates/white.html
Labels: chore

#162 Fix : 환율 API 대체
  countries/templates/countries/detail.html
Labels: fix

#163 Fix : 환율 API 다시 적용
  countries/templates/countries/detail.html
Labels: chore

#164 Fix : 뉴스 스크롤링
  countries/templates/countries/detail.html
Labels: fix

#165 Fix : accounts detail 사이즈 조절
  accounts/templates/accounts/detail.html
Labels: fix

#166 Fix : accounts detail 댓글 목록 이미지 삭제
  accounts/templates/accounts/detail.html
Labels: chore, fix

#167 Fix : 공지사항 수정, 커뮤 인덱스 수정
  communities/templates/communities/index.html
  communities/templates/communities/main.html
Labels: chore
