Repository jincde/before-trip, pull requests merged in 2022-11, with the labels that each got.

#2 Feat: accounts app crud 기본구성 완료
  PJT/settings.py
  PJT/urls.py
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/forms.py
  accounts/models.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/index.html
  accounts/templates/accounts/list.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
Labels: BE, feature

#3 Feat : Base 생성
  PJT/settings.py
  static/css/main.css
  templates/base.html
Labels: feature

#8 Chore: countries/index.html 수정
  countries/templates/countries/index.html
  countries/templates/country/detail.html
  countries/templates/country/index.html
  static/js/index_map_click.js
  templates/map.html
Labels: chore

#9 Style: CSS 동작 확인
  PJT/urls.py
  communities/models.py
  communities/static/communities/css/style.css
  communities/templates/communities/review.html
  communities/urls.py
  communities/views.py
  countries/urls.py
Labels: style

#10 Feat : 내비게이션 바 반응형 구현
  accounts/templates/accounts/index.html
  static/css/main.css
  templates/base.html
Labels: FE, feature

#11 Feat: 커뮤니티 index 연결
  communities/models.py
  communities/templates/communities/index.html
  communities/urls.py
  communities/views.py
  countries/admin.py
  countries/urls.py
Labels: feature

#12 Feat: accounts detail 페이지 이미지 띄우기 완료
  PJT/urls.py
  accounts/forms.py
  accounts/models.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/index.html
  accounts/templates/accounts/list.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  accounts/urls.py
  accounts/views.py
Labels: FE, BE, feature

#13 Feat : 스크롤 시 헤더 색상 변경
  static/css/main.css
  templates/base.html
Labels: FE, feature

#14 Fix : 내브바 커졌을 때 리스트그룹 남아있던 현상 수정
  accounts/templates/accounts/index.html
  countries/urls.py
  static/css/main.css
  templates/base.html
Labels: fix

#16 Feat: google 소셜로그인 기능 추가
  PJT/settings.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/list.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  static/images/google.png
Labels: FE, BE, feature

#17 Style : PC 전체 길이 수정
  static/css/main.css
  static/css/map.css
  templates/base.html
  templates/map.html
Labels: style

#18 Style : 로그인 폼 스타일 추가
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  static/css/accounts.css
  templates/not_nav_base.html
Labels: FE, style

#20 Test: Google Calendar 인증 및 이벤트 객체생성 테스트
  communities/templates/communities/test.html
  communities/views.py
Labels: test

#21 Style : 회원가입 폼 스타일 추가, input file 스타일 수정
  PJT/settings.py
  accounts/templates/accounts/signup.html
  static/css/accounts.css
Labels: FE, style

#23 Fix : 회원가입 후 오류 수정
  accounts/templates/accounts/signup.html
  accounts/views.py
Labels: fix

#24 Feat: 커뮤니티 섬머노트
  PJT/settings.py
  PJT/urls.py
  communities/admin.py
  communities/forms.py
  communities/models.py
  communities/templates/communities/detail.html
  communities/templates/communities/form.html
  communities/templates/communities/index.html
  communities/urls.py
  communities/views.py
  requirements.txt
  templates/base.html
Labels: BE, feature

#25 Style: 리뷰 인덱스 페이지 스타일 추가
  communities/static/communities/css/style.css
  communities/templates/communities/index.html
Labels: style

#27 Fix : JS 겹치는 코드 삭제
  .gitignore
  countries/templates/countries/detail.html
  static/img/google-logo.webp
  static/img/logo1.png
  static/img/logo2.png
  static/img/menu.png
  static/img/naver-logo.png
  templates/base.html
Labels: fix

#29 Chore: review 인덱스 디테일 페이지 연결
  communities/forms.py
  communities/templates/communities/index.html
  communities/views.py
Labels: chore

#30 Style : 국가 디테일 페이지 반응형 구현
  countries/templates/countries/detail.html
  static/css/main.css
  templates/base.html
Labels: FE

#31 Style: 페이지 로딩 화면 수정 Test: 캘린더 iframe 테스트
  communities/templates/communities/test.html
  communities/tests.py
  communities/urls.py
  communities/views.py
  static/images/Rocket.gif
  static/images/loading.gif
  templates/base.html
Labels: style, test

#32 Feat: json 파싱해서 db저장하는 기능 추가 완료
  country.py
Labels: BE, feature

#34 Chore: 디테일 base.html 상속
  communities/static/communities/img/create.png
  communities/static/communities/img/header-review.jpg
  communities/templates/communities/detail.html
Labels: chore

#37 Feat: 뉴스api 끌어온거 json으로 전환 완료
  news.api.add.json.py
  news.json
Labels: BE, feature

#38 Style: 후기 디테일 스타일 추가
  communities/static/communities/css/style.css
  communities/templates/communities/detail.html
Labels: FE, style

#39 Fix : PC화면에서 사라지지 않던 햄버거 메뉴 수정
  static/css/main.css
  templates/base.html
Labels: bug, fix
